networks:
  custom-fields-network:
    driver: bridge

volumes:
  mysql-data:
services:
  custom-fields-mysql:
    image: bitnami/mysql:8.2.0
    container_name: custom-fields-mysql
    environment:
      MYSQL_ROOT_USER: dev
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: custom_fields_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/bitnami/mysql/data
    networks:
      - custom-fields-network
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
